# Generated by Django 4.2.17 on 2024-12-17 17:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_remove_question_id_question_uid_delete_useranswer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="text", new_name="question",
        ),
        migrations.RemoveField(model_name="question", name="correct_option",),
        migrations.RemoveField(model_name="question", name="option_a",),
        migrations.RemoveField(model_name="question", name="option_b",),
        migrations.RemoveField(model_name="question", name="option_c",),
        migrations.RemoveField(model_name="question", name="option_d",),
        migrations.AddField(
            model_name="question", name="marks", field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("option", models.CharField(max_length=250)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
