# Generated by Django 4.2.17 on 2024-12-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_customuser_groups_customuser_user_permissions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option", old_name="question", new_name="refer_question",
        ),
    ]
