# Generated by Django 4.2.17 on 2024-12-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_rename_question_option_refer_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option", old_name="refer_question", new_name="question",
        ),
    ]
