# Generated by Django 4.2.17 on 2024-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_rename_refer_question_option_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser", name="marks", field=models.IntegerField(default=0),
        ),
    ]
