# Generated by Django 4.2.17 on 2024-12-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0013_attemptedquestion"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="groups",),
        migrations.RemoveField(model_name="customuser", name="user_permissions",),
        migrations.AddField(
            model_name="question",
            name="attempted",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(name="AttemptedQuestion",),
        migrations.DeleteModel(name="CustomUser",),
    ]
